// 新封装组件按字母顺序插入相应位置方便查找
// 对外暴露名字和文件名、自定义名字一致
const Widgets = {
	get AlertImall() { return require('./modal/AlertImall').default; },
	get AndroidCheckAlert() { return require('./modal/AndroidCheckAlert').default; },
	get Arrow() { return require('./icon/Arrow').default },
	get Banner() { return require('./banner/Banner').default; },
	get BannerA() { return require('./banner/BannerA').default; },
	get BaseView() { return require('./baseView/BaseView').default; },
	get CheckBox() { return require('./checkBox/CheckBox').default; },
	get CoustomTabBar() { return require('./scrollableTabView/CoustomTabBar').default; },
	get CustomMaskBoard() { return require('./modal/CustomMaskBoard').default; },
	get DataController() { return require('./controller/DataController').default; },
	get DatePicker() { return require('./picker/DatePicker').default; },
	get EasyToast() { return require('./maskModal/EasyToast').default; },
	get Gallery() { return require('./gallery/Gallery').default; },
	get ImageUploader() { return require('./imageUploader/ImageUploader').default; },
	get ImagePicker() { return require('./picker/ImagePicker').default; },
	get InputAlert() { return require('./modal/InputAlert').default; },
	get ItemPicker() { return require('./picker/ItemPicker').default; },
	get Loading() { return require('./loading/Loading').default; },
	get MaskModal() { return require('./maskModal/MaskModal').default; },
	get NavBar() { return require('./nav/NavBar').default; },
	get NewRefreshableListView() { return require('./listview/NewRefreshableListView').default; },
	get NumberInput() { return require('./numberInput/NumberInput').default; },
	get NoticeBanner() { return require('./banner/NoticeBanner').default; },
	get NoticeBanners() { return require('./banner/NoticeBanners').default; },
	get RefreshableListView() { return require('./listview/RefreshableListView').default; },
	get RightNavBtn() { return require('./nav/RightNavBtn').default; },
	get ScalePopupView() { return require('./modal/ScalePopupView').default; },
	get ScrollableTabBar() { return require('./scrollableTabView/ScrollableTabBar'); },
	get Separator() { return require('./separator/Separator').default; },
	get StarRating() { return require('./star/StarRating').default; },
	get TabBar() { return require('./tab/TabBar').default; },
	get Text() { return require('./text/Text').default; },
	get TextInput() { return require('./textinput/TextInput').default; },
	get Timeable() { return require('./timer/Timeable').default; },
	get TextInputC() { return require('./textinput/TextInputC').default; },
	get Alerts() { return require('./modal/Alerts').default; },
	get Toast() { return require('./toast'); },
	get Page() { return require('./page/Page').default; },
	get PopModal() { return require('./modal/PopModal').default; },
	get PullView() { return require('./pulltorefresh/PullView').default; },
	get WebViewPage() { return require('./webViewPage/WebViewPage').default; },
	get Panel() { return require('./panel/Panel').default; },
}
module.exports = Widgets;