import Styles from 'future/public/lib/styles/Styles';
import { PixelRatio } from 'react-native';
var SCREEN_WIDTH = require('Dimensions').get('window').width;
var SCREEN_HEIGHT = require('Dimensions').get('window').height;
export default styles = Styles.create({
    container: {
        flex:1,
        backgroundColor:'#f0f0f0'
    },
    bottomMenueContainer:{
        width:SCREEN_WIDTH,
        height:50,
        backgroundColor:'#fff',
        flexDirection:'row',
        alignItems:'center'
    },
    allSelectBtn:{
        width:40,
        height:50,
        justifyContent:'center'
    },
    allSelectImg:{
        width: 16, 
        height: 16, 
        marginLeft:15
    },
    allSelect:{
        width:40,
        height:20,
        fontSize:14,
        color:'#333'
    },
    stocksListInfo:{
        height:50,
        paddingRight:9
    },
    stocksListTotal:{
        fontSize:13,
        color:'#333',
        marginTop:8,
        flex:1,
        textAlign:'right'
    },
    stocksListTotalPrice:{
        
        fontSize:13,
        color:'#FF6600'
    },
    favourable:{
        flex:1,
        fontSize:10,
        color:'#666',
        marginTop:6,
        textAlign:'right'
    },
    settleBtn:{
        width:110,
        height:50,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'#34457D'
    },
    settleBtnTitle:{
        color:'#fff',
        fontSize:16
    },
    cashOnDelivery:{
        alignItems:'center',
        width:68,
        height:50,
        justifyContent:'center'
    },
    menuImg:{
        width:20,
        height:15,
    },
    menuTxt:{
        color:'#333',
        fontSize:10,
        marginTop:4
    },
    cartShop:{
        width:SCREEN_WIDTH,
        flex:1,
        borderBottomWidth:1,
        borderBottomColor:'#f0f0f0',
        marginTop:0.5
    },
    cartShopCheckView:{
        width:SCREEN_WIDTH,
        height:49,
        flexDirection:'row',
        alignItems:'center',
        backgroundColor:'#fff'
    },
    cartShopCheckBtn:{
        justifyContent:'center',
        alignItems:'center',
        height:49,
        width:50
    },
    cartShopCheckImg:{ width: 16, height: 16},
    cartShopTitle:{fontSize:14,color:'#333'},
    cartShopCaptureView:{
        width:SCREEN_WIDTH,
        height:0.5,
        backgroundColor:'#fefefe',
        marginLeft:49-SCREEN_WIDTH
    },
    orderPresentView:{
        flex:1,
        width:SCREEN_WIDTH,
        backgroundColor:'#fff',
        flexDirection:'row'
    },
    orderTitleView:{marginLeft:15,marginTop:10},
    orderTitle:{fontSize:12,color:'#666'},
    orderPresentItems:{paddingBottom:10,marginLeft:20},
    orderPresentItem:{
        width:SCREEN_WIDTH-100,
        flexDirection:'row',
        justifyContent:'space-between'
    },
    orderPresentNm:{marginTop:10,fontSize:12,color:'#53606A'},
    orderPresentNum:{marginTop:10,fontSize:12,color:'#53606A'},
    newPlanModal:{
        width:270,
        height:150,
        top:100,
        backgroundColor:'rgba(234,234,234,0.90)',
        borderRadius:12,
        alignItems:'center',
        justifyContent:'space-between'
    },
    plan_NewBtn:{fontSize:17,color:'#333',marginVertical:15},
    plan_inputNm:{ 
        width: 240, 
        height: 33, 
        fontSize: 14, 
        padding: 0 ,
        backgroundColor:'#fff',
        marginTop:3,
        marginLeft:5
    },
    plan_cancel:{
        marginTop:15,
        height:45,
        flexDirection:'row',
        borderTopWidth:1/PixelRatio.get(),
        borderColor:'#999'
    },
    plan_cancelBtn:{
        flex:1,
        justifyContent:'center',
        alignItems:'center',
        borderRightWidth:1/PixelRatio.get(),
        borderColor:'#999'
    },
    plan_cancelTitle:{color:'#007aff',fontSize:16},
    plan_sureBtn:{
        flex:1,
        justifyContent:'center',
        alignItems:'center'
    },
    plan_sureTitle:{color:'#007aff',fontSize:16},
    mask_PlanSelect:{
        width:SCREEN_WIDTH,
        height:310,
        backgroundColor:'#fff',
        marginTop:SCREEN_HEIGHT-374,
        
    },
    mask_PlanSelectScroll:{
        width:SCREEN_WIDTH,
    },
    mask_PlanSelectTitle:{
        marginTop:17,
        fontSize:16,
        color:"#333",
        marginLeft:13,
        fontWeight:'bold'
    },
    mask_NewPlan:{flexDirection:'row',marginLeft:13},
    mask_NewPlanImg:{ marginTop:33,width: 16, height: 16},
    mask_NewPlanTxt:{
        marginTop:33,
        fontSize:16,
        color:"#333",
        marginLeft:16
    },
    mask_PlanItem:{flexDirection:'row',marginLeft:13,alignItems:'center'},
    mask_PlanItemImg:{ marginTop:33,width: 16, height: 16},
    mask_PlanItemTxt:{
        marginTop:33,
        fontSize:16,
        color:"#333",
        marginLeft:16
    }
});